import { useId } from 'vue';

// Namespaced so ids generated by the library never collide with ids from the
// host app or other component libraries sharing the same page.
export function useGeneratedId() {
    return `cui-${useId()}`;
}
